config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: 'quizzes#index'

  resources :quizzes do
    get 'take'
    patch 'grade' => 'quizzes#grade'
  end

  get 'about' => 'about#index'

  get 'tutorial' => 'tutorial#index'

  devise_for :users

  #if Rails.env.production?
  get '404' => 'application#page_not_found'
  #end
  match '*a' => 'application#page_not_found', via: [:get, :post]

  # NOTES:
  # Use Rails.application.reload_routes! in paused debug console to force routes to reload

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    # @quizzes = Quiz.user_quizzes(current_user.id)
    @quizzes = Quiz.viewable_quizzes(current_user.id)
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new(:user_id => current_user.id)
    @questions = @quiz.questions.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user_id = current_user.id

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # take a quiz
  # /quizzes/1/take
  def take
    @quiz = Quiz.find(params[:quiz_id])
    render :take # redundant...but here for clarity
  end

  # Note: this is currently 'hacked' to use the PATCH verb for routing
  def grade
    @quiz = Quiz.new(quiz_params)
    @quiz.show_answers = Quiz.find(quiz_params[:id]).show_answers # add value back in

    total_questions = @quiz.number_of_questions
    total_correct = @quiz.number_questions_correct

    @score = (total_correct.to_f / total_questions.to_f * 100.0).round(2)

    render :grade

  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def quiz_params
    params.require(:quiz).permit(
      :title, :description, :user_id, :id, :show_answers, :public,
      questions_attributes: [ :id, :question, :answer, :_destroy, :user_answer, :question_type, :hint ]
    )
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.slim
javascript:
  $('[data-form-prepend]').click( function(e) {
      var obj = $( $(this).attr('data-form-prepend') );
      obj.find('input, select, textarea').each( function() {
          $(this).attr( 'name', function() {
              return $(this).attr('name').replace( 'new_record', (new Date()).getTime() );
          });
      });
      obj.insertBefore( this );
      return false;
  });

/! TODO: add modal for adding/editing questions rather than inline; only display inline

/! TODO: add javascript handling for question_type changes

= form_for @quiz, html: {class: 'form-group'} do |form|
  - if quiz.errors.any?
    #error_explanation
      h2
        = pluralize(quiz.errors.count, "error")
        |  prohibited this quiz from being saved:
      ul
        - quiz.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title, id: :quiz_title, class: 'form-control'
  .field
    = form.label :description
    = form.text_area :description, id: :quiz_description, class: 'form-control'
  .field
    = form.label :show_answers, 'Show correct answers when displaying score to user?'
    = form.check_box :show_answers, id: :quiz_show_answers, class: 'form-control checkbox-width'
  .field
    = form.label :public, 'Allow anyone to take quiz (make it public)?'
    = form.check_box :public, id: :quiz_public, class: 'form-control checkbox-width'

  /! TODO: add partials for all question_types

  .field
    = form.hidden_field :user_id, id: :user_id
  h3
    | Questions
  p
    = form.fields_for :questions do |f|
      = render 'question_fields', f: f
  p
    = link_to_add_fields('Add new question', form, :questions)
  .actions
    = form.submit class: 'btn btn-primary'

app/views/quizzes/_question_fields.html.slim
.form-group
  .box
    / .field
      / = f.label :question_type
      / = f.select :question_type, Question.question_types.keys, id: :question_type, class: 'form-control'
    .field
      = f.label :question
      = f.text_field :question, id: :question, class: 'form-control'
    .field
      .font-italic
        = f.label :hint, 'Hint or tip to show user (optional)'
      = f.text_field :hint, id: :hint, class: 'form-control'
    .field
      = f.label :answer
      = f.text_field :answer, id: :answer, class: 'form-control'
    div[style="display: inline"]
      = f.check_box :_destroy
      = f.label :_destroy, 'Delete question'

app/views/quizzes/_take_form.html.slim
= form_for @quiz, :url => {:action => "grade"} do |form|
  - if quiz.errors.any?
    #error_explanation
      h2
        = pluralize(quiz.errors.count, "error")
        |  prohibited this quiz from being saved:
      ul
        - quiz.errors.full_messages.each do |message|
          li
            = message
  .field
    b
      = form.label 'Description: '
    = ' ' + @quiz.description
  .field
    = form.hidden_field :user_id, id: :user_id
    = form.hidden_field :id, id: :quiz_id
  h3
    | Questions
  p
    = form.fields_for :questions do |f|
      = render 'take_quiz_question_fields', f: f
  .actions
    = form.submit "Grade Quiz", class: 'btn btn-primary'
  br

app/views/quizzes/_take_quiz_question_fields.html.slim
.form-group
  .box
    .field
      b
        = f.label 'Question: '
      = ' ' + f.object.question
    - unless f.object.hint == ''
      .field.font-italic
        b
          = f.label 'Hint: '
        = ' ' + f.object.hint
    .field
      b
        = f.label :answer
      = f.text_field :user_answer, id: :user_answer, class: 'form-control'

app/views/quizzes/edit.html.slim
.form-profile-div.quiz-form
  h2
    | Editing Quiz
  = render 'form', quiz: @quiz
  = link_to 'Show', @quiz
  |  | 
  = link_to 'Back', quizzes_path

app/views/quizzes/grade.html.slim
.quiz-form.form-profile-div
  .text-center
    | You correctly answered
    b
      = ' ' + @quiz.number_questions_correct.to_s + ' '
    | out of
    b
      = ' ' + pluralize(@quiz.number_of_questions,'question') + ' '
    br
    | for a score of
    b
      = ' ' + @score.to_s
      | %
    | . 
  br
  - if @quiz.show_answers?
    ol
      - @quiz.questions.each do |q|
        li
          b
            = q.question
          ul
            li
              | Correct answer: 
              b
                = q.answer
            li
              | Your answer: <div class="display-inline font-weight-bold 
              - if q.correct?
                | correct
              - else
                | incorrect
              | "> 
              = q.user_answer
  - else
    p
      i
        | Display of answers disabled for this quiz.
  p
    = link_to 'Back to Quizzes', quizzes_path

app/views/quizzes/index.html.slim
.form-profile-div.quiz-main
  h2
    | Quizzes
  - unless @quizzes.blank?
    table.table.table-striped
      thead
        tr
          th
            | Title
          th
            | Description
          th
            | Number of Questions
          th
            | Show Answers?
          th
            | Public Quiz?
          th[colspan="3"]
      tbody
        - @quizzes.each do |quiz|
          tr
            td
              = quiz.title
            td
              = quiz.description
            td
              = quiz.number_of_questions
            td
              - if quiz.show_answers?
                | Yes
              - else
                | No
            td
              - if quiz.public?
                | Yes
              - else
                | No
            td
              = link_to 'Take', 'quizzes/'+quiz.id.to_s+'/take', class: 'btn btn-success', id: 'take_quiz',  data: { toggle: 'tooltip', placement: 'top', title: 'Take your quiz!' }
            - if quiz.belongs_to_user(current_user.id)
              td
                = link_to 'Edit', edit_quiz_path(quiz), class: 'btn btn-secondary', id: 'edit_quiz',  data: { toggle: 'tooltip', placement: 'top', title: 'Edit your quiz!' }
              td
                = link_to 'Delete', quiz, method: :delete, id: 'delete_quiz',
                data: { confirm: 'Are you sure you would like to delete quiz: ' + \
                quiz.title + '?' + ' Deleted quizzes cannot be recovered.',
                toggle: 'tooltip', placement: 'top', title: 'Delete your quiz!' },
                class: 'btn btn-danger'
            - else
              td
              td
  - else
    .instruction
      | There are no quizzes. Create one!
      br
      .font-italic
        = link_to 'Click here for a tutorial', 'tutorial#index'
        |   on how to get started!
  br
  = link_to 'New Quiz', new_quiz_path, id: :new_question, class: 'btn btn-primary', id: 'create_quiz'
  span id = "new_text" class = "text"| Create your quiz!

style |
 css:

   .text {
     position: relative;
     display: inline-block;
     border-bottom: 1px dotted black;
   }

   .text {
     visibility: hidden;
     width: 120px;
     background-color: black;
     color: #fff;
     text-align: center;
     border-radius: 6px;
     padding: 5px 0;

     /* Position the tooltip */
     position: absolute;
     z-index: 1;
     bottom: 100%;
     left: 50%;
     margin-left: -60px;
   }

   .text:hover {
     visibility: visible !important;
   }

app/views/quizzes/new.html.slim
.form-profile-div.quiz-form
  h2
    | New Quiz
  = render 'form', quiz: @quiz
  = link_to 'Back', root_path,
          data: {confirm: "Are you sure? If you go back your changes will not be saved and your quiz will not be created."}, method: :get, class: 'btn btn-danger'

app/views/quizzes/show.html.slim
.form-profile-div.quiz-show
  p
    strong
      | Title:&nbsp;
    = @quiz.title
  p
    strong
      | Description:&nbsp;
    = @quiz.description
  p
    strong
      | Show correct answers when displaying score to user?
    - if @quiz.show_answers?
      |  Yes
    - else
      |  No
  p
    strong
      | Quiz viewable and can be taken by anyone (public)?
    - if @quiz.public?
      |  Yes
    - else
      |  No
  h3
    | Questions
  div
    - unless @quiz.questions.blank?
      - @quiz.questions.each do |q|
        div
          b
            | Question:&nbsp;
          = q.question
        - unless q.hint == ''
          .field.font-italic
            b
              | Hint:
            = ' ' + q.hint
        div
          b
            | Answer:&nbsp;
          = q.answer
        br
    - else
      div.font-italic
        | There are no questions in this quiz. You should add some.
  = link_to 'Edit', edit_quiz_path(@quiz)
  |  | 
  b
    = link_to 'Back to Quizzes', quizzes_path
  |  |
  b
    = link_to 'Take this quiz', "/quizzes/#{@quiz.id}/take"

app/views/quizzes/take.html.slim
.form-profile-div.quiz-form
  h2
    | Taking Quiz "
    = @quiz.title
    | "
  = render 'take_form', quiz: @quiz
  = link_to 'Back to Quizzes', quizzes_path